name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Run database migrations
        run: php artisan migrate --force

      # Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Start Laravel server and ngrok
      - name: Start Laravel server and ngrok
        run: |
          # Start Laravel server
          php artisan serve --port=8000 &

          # Install ngrok
          curl -s https://ngrok.com/download | sudo tar -xz -C /usr/local/bin ngrok

          # Authenticate ngrok
          /usr/local/bin/ngrok cr_2gRhaa4vpdwtEHDVOosrrGt6Cch

          # Start ngrok and redirect traffic from ngrok URL to localhost:8000
          /usr/local/bin/ngrok http 8000 --bind-tls=true --region=us &
          sleep 5  # Wait for ngrok to start

          # Get ngrok URL
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"

          # Set ngrok URL as environment variable
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        run: |
          php artisan test
