name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Run database migrations
        run: php artisan migrate --force

      # Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Install ngrok
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
          | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
          | sudo tee /etc/apt/sources.list.d/ngrok.list \
          && sudo apt update \
          && sudo apt install ngrok
          
          # Move ngrok to specific location
          sudo mv /usr/bin/ngrok /usr/local/bin/ngrok

      # Start Laravel server
      - name: Start Laravel server
        run: php artisan serve --port=8000 &

      # Start ngrok to expose the Laravel server
      - name: Start ngrok
        run: ngrok http 8000
