name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Run database migrations
        run: php artisan migrate --force

      # Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Install ngrok using Snap
      - name: Install ngrok
        run: sudo snap install ngrok

      # Authenticate ngrok
      - name: Authenticate ngrok
        run: ngrok authtoken 1wV4b9ZH1b9xROsGgNRIDRW2b9O_31XFQNuqasUAGbfvsCjtj

      # Start Laravel server
      - name: Start Laravel server
        run: php artisan serve --port=8000 &

      # Start ngrok to expose the Laravel server
      - name: Start ngrok
        run: ngrok http 8000
